const API=(window.APP_CONFIG?.API_URL||'').replace(/\/$/,''),V=document.querySelector('#view'),T=document.querySelector('#toast');
let adminViewVersion=0;
let logViewState={page:1,filters:{limit:'25'}};
const A=[['control','CTRL','Control'],['execution','EXEC','Execution'],['defending','DEF','Defending'],['reaction_time','RT','Reaction Time'],['chemistry','CHEM','Chemistry'],['game_sense','GS','Game Sense']];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tier=n=>n>=257?'S':n>=215?'A':n>=172?'B':n>=129?'C':n>=86?'D':n>=43?'E':'F';
const date=x=>x?new Date(/^\d{4}-\d{2}-\d{2}$/.test(String(x))?String(x)+'T00:00:00':x).toLocaleDateString(undefined,{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
function codeHTML(id='code'){return `<div class="code" data-code="${id}">${[0,1,2,3,4,5].map(i=>`<input maxlength="1" inputmode="numeric" aria-label="Digit ${i+1}">`).join('')}</div>`}
function wireCodes(root=V){root.querySelectorAll('.code').forEach(b=>{let a=[...b.querySelectorAll('input')];a.forEach((x,i)=>{x.oninput=()=>{x.value=x.value.replace(/\D/g,'').slice(-1);if(x.value)a[i+1]?.focus()};x.onkeydown=e=>{if(e.key==='Backspace'&&!x.value)a[i-1]?.focus()};x.onpaste=e=>{e.preventDefault();let s=e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6);if(!s)return;a.forEach((input,j)=>input.value=s[j]||'');a[Math.min(s.length,5)]?.focus()}})})}
function getCode(id='code'){return [...V.querySelector(`[data-code="${id}"]`).querySelectorAll('input')].map(x=>x.value).join('')}
// A tab-scoped token also supports browsers that block cross-site cookies.
let sessionToken='';try{sessionToken=sessionStorage.getItem('admin_session_token')||''}catch{}
function saveSessionToken(token){sessionToken=token||'';try{if(sessionToken)sessionStorage.setItem('admin_session_token',sessionToken);else sessionStorage.removeItem('admin_session_token')}catch{}}
async function api(path,opt={}){if(!API||API.includes('REPLACE-WITH'))throw Error('Set API_URL in config.js first.');let r=await fetch(API+path,{...opt,credentials:'include',headers:{'Content-Type':'application/json',...(sessionToken?{Authorization:'Bearer '+sessionToken}:{}),...(opt.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok){let error=Error(d.error||`Request failed (${r.status})`);error.status=r.status;throw error}if(path==='/api/login'&&d.session_token)saveSessionToken(d.session_token);if(path==='/api/logout'){saveSessionToken('');logViewState={page:1,filters:{limit:'25'}}}return d}

function render(s){V.innerHTML=s;wireCodes();}
let toastTimer;
function msg(s){clearTimeout(toastTimer);T.textContent=s;T.classList.add('show');toastTimer=setTimeout(()=>T.classList.remove('show'),2300)}
async function home(){try{let {players}=await api('/api/players');render(`<div class="hero"><div class="eyebrow">PLAYER DATABASE</div><h1>Players</h1><p>Current ratings, classes and development records.</p></div><div class="toolbar"><input id="q" placeholder="Search players or classes…"></div><div id="cards" class="grid"></div>`);let draw=()=>{let q=document.querySelector('#q').value.toLowerCase(),p=players.filter(x=>(x.name+' '+x.class_name).toLowerCase().includes(q));document.querySelector('#cards').innerHTML=p.length?p.map(card).join(''):`<div class="empty" style="grid-column:1/-1">No players found.</div>`};document.querySelector('#q').oninput=draw;draw()}catch(e){render(`<div class="empty">${esc(e.message)}</div>`)}}
function card(p){return `<a class="player-card" href="#/player/${encodeURIComponent(p.id)}"><div class="card card-surface"><div class="player-head"><div><div class="name">${esc(p.name)}</div><div class="class">${esc(p.class_name||'Class undetermined')}${p.locked?' · LOCKED':''}</div></div><span class="badge ${p.overall_tier}">${p.overall_tier}</span></div>${A.map(([k,s])=>`<div class="barrow"><span>${s}</span><div class="bar"><i style="width:${Math.min(100,(p[k]||0)/3)}%"></i></div><b>${tier(p[k])}</b></div>`).join('')}<div class="meta">${A.reduce((n,[k])=>n+Number(p[k]||0),0)} / 1800 · ${date(p.assessed_at)}</div></div></a>`}
async function player(id){try{let {player:p,history}=await api('/api/players/'+encodeURIComponent(id)),sum=A.reduce((n,[k])=>n+Number(p[k]||0),0);render(`<a href="#/" class="meta">← All players</a><div class="hero" style="margin-top:20px"><div class="eyebrow">PLAYER PROFILE</div><h1>${esc(p.name)}</h1><p>${esc(p.class_name||'Class undetermined')} · Overall <b>${esc(p.overall_tier)}</b></p></div><div class="two"><section class="card"><h2>Attributes</h2><table class="table"><tr><th>Attribute</th><th>Points</th><th>Tier</th></tr>${A.map(([k,,n])=>`<tr><td>${n}</td><td>${p[k]} / 300</td><td><b>${tier(p[k])}</b></td></tr>`).join('')}</table><div class="stats"><div class="stat"><b>${sum}</b><span>Total / 1800</span></div><div class="stat"><b>${(sum/6).toFixed(2)}</b><span>Average / 300</span></div><div class="stat"><b>${tier(sum/6)}</b><span>Attribute Tier</span></div></div></section><aside><section class="card"><h2>Playstyle</h2><p>${esc(p.playstyle||'No description recorded.')}</p><h3>Strengths</h3><p>${esc(p.strengths||'—')}</p><h3>Weaknesses</h3><p>${esc(p.weaknesses||'—')}</p></section><section class="card" style="margin-top:15px"><h2>Assessment History</h2>${history.length?history.slice().reverse().map(h=>`<div class="listrow"><div><b>${date(h.assessed_at)}</b><div class="meta">${h.total} / 1800 · Overall ${h.overall_tier}</div></div></div>`).join(''):'<p>No history.</p>'}</section></aside></div>`)}catch(e){render(`<div class="empty">${esc(e.message)}</div>`)}}
function login(account,setupInvitation=''){if(!account)return accounts();let invitation=!account.code_ready&&account.invitation_expires_at>Date.now();render(`<div class="login"><h1>Sign in</h1><p>Access <strong>${esc(account.name)}</strong> with ${account.code_ready?'your personal code':invitation?'your one-time setup invitation':'the default admin code to set up your account'}.</p><section class="card">${invitation?'<input id="invitation" aria-label="Setup invitation" placeholder="Setup invitation" autocomplete="off">':codeHTML()}<div id="err" class="error"></div><div class="login-actions"><button id="go">Continue</button><button id="chooseAccount" class="secondary">Choose another account</button></div></section></div>`);if(invitation&&setupInvitation)document.querySelector('#invitation').value=setupInvitation;document.querySelector('#chooseAccount').onclick=accounts;document.querySelector('#go').onclick=async()=>{let code=invitation?document.querySelector('#invitation').value.trim():getCode();let button=document.querySelector('#go');button.disabled=true;try{let result=await api('/api/login',{method:'POST',body:JSON.stringify({code,account_id:account.id})});if(result.setup_required)setupPersonalCode(account,code);else await admin()}catch(e){document.querySelector('#err').textContent=e.message;if(invitation&&Date.now()>=account.invitation_expires_at){let data=await api('/api/accounts');login(data.accounts.find(x=>x.id===account.id));msg('Invitation expired. Use the default code to start setup.')}}finally{button.disabled=false}}}
function setupPersonalCode(account,setupCode){render(`<div class="login"><h1>Create your code</h1><p>Choose a personal six-digit code for <strong>${esc(account.name)}</strong>.</p><section class="card"><h2>New code</h2>${codeHTML('newCode')}<h2>Confirm code</h2>${codeHTML('confirmCode')}<div id="err" class="error"></div><div class="login-actions"><button id="saveCode">Save and sign in</button><button id="cancelCode" class="secondary">Cancel</button></div></section></div>`);V.querySelectorAll('.code input').forEach(x=>x.type='password');document.querySelector('#cancelCode').onclick=accounts;document.querySelector('#saveCode').onclick=async()=>{let new_code=getCode('newCode'),confirm_code=getCode('confirmCode');if(!/^\d{6}$/.test(new_code)||new_code!==confirm_code){document.querySelector('#err').textContent='Enter and confirm the same six-digit code.';return}let button=document.querySelector('#saveCode');button.disabled=true;try{await api('/api/login',{method:'POST',body:JSON.stringify({account_id:account.id,code:setupCode,new_code,confirm_code})});await admin()}catch(e){document.querySelector('#err').textContent=e.message}finally{button.disabled=false}}}

async function admin(){try{let s=await api('/api/session');if(!s.authenticated)return accounts();render(`<div class="admin"><div class="hero"><div class="eyebrow">ADMINISTRATOR</div><h1>Manage database</h1><p>Signed in as <strong>${esc(s.account.name)}</strong>.</p></div><div class="admin-navigation"><div class="tabs"><button data-tab="players">Players</button><button data-tab="new">New Player</button><button data-tab="settings">Settings</button><button data-tab="logs">Logs</button>${s.account.is_primary?'<button data-tab="accounts">Manage Accounts</button>':''}</div><div class="admin-session-actions"><button id="switch" class="secondary">Switch account</button><button class="secondary" id="out">Sign out</button></div></div><div id="adminContent"></div></div>`);document.querySelector('#switch').onclick=()=>accounts();document.querySelector('#out').onclick=async()=>{await api('/api/logout',{method:'POST'});location.hash='#/';home()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>adminTab(b.dataset.tab));adminTab('players')}catch(e){login()}}
async function adminTab(tab){selectAdminTab(tab);let c=document.querySelector('#adminContent'),version=++adminViewVersion;if(tab==='logs'){logs();return}if(tab==='accounts'){manageAccounts();return}if(tab==='new'){c.innerHTML=form();wireForm();return}if(tab==='settings'){settings();return}try{let {players}=await api('/api/players');if(version!==adminViewVersion||!c.isConnected)return;c.innerHTML=`<section class="card">${players.length?players.map(p=>`<div class="listrow"><div><b>${esc(p.name)}</b><div class="meta">${esc(p.class_name||'Class undetermined')} · ${p.overall_tier}${p.locked?' · LOCKED':''}</div></div><div class="actions"><button class="secondary" ${p.locked?'disabled title="Unlock this player before editing"':''} onclick="edit('${p.id}')">Edit</button><button class="secondary" onclick="lock('${p.id}',${!!p.locked})">${p.locked?'Unlock':'Lock'}</button><button class="danger" onclick="del('${p.id}')">Delete</button></div></div>`).join(''):'<p>No players yet.</p>'}</section>`}catch(e){if(version===adminViewVersion&&c.isConnected)c.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function field(n,l,v='',type='text',full=false){return `<div class="field ${full?'full':''}"><label for="field-${n}">${l}</label>${full?`<textarea id="field-${n}" name="${n}">${esc(v)}</textarea>`:`<input id="field-${n}" name="${n}" type="${type}" value="${esc(v)}" ${type==='number'?'min="0" max="300"':''}>`}</div>`}
function localToday(){let d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function form(p={}){return `<section class="card"><h2>${p.id?'Edit':'New'} Player</h2><form id="pf"><div class="formgrid">${field('name','Player name',p.name||'')} ${field('class_name','Class',p.class_name||'')}${A.map(([k,,n])=>field(k,n,p[k]??0,'number')).join('')}${field('overall_tier','Overall tier',p.overall_tier||'B')}${field('assessed_at','Assessment date',p.assessed_at?String(p.assessed_at).slice(0,10):localToday(),'date')}${field('playstyle','Playstyle',p.playstyle||'','text',true)}${field('strengths','Strengths',p.strengths||'','text',true)}${field('weaknesses','Weaknesses',p.weaknesses||'','text',true)}</div><div style="text-align:right;margin-top:16px"><button>Save</button></div></form></section>`}
function selectAdminTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>{let active=b.dataset.tab===tab;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false')})}
function showEditLock(form){let notice=form.querySelector('.edit-lock-notice');if(!notice){notice=document.createElement('div');notice.className='notice edit-lock-notice';notice.setAttribute('role','status');notice.textContent='This player has been locked. Your unsaved changes remain here, but will not be applied to the assessment. Return to Players to unlock the record before editing again.';form.prepend(notice)}form.querySelectorAll('input,textarea,select,button').forEach(x=>x.disabled=true)}
function wireForm(id=null){let form=document.querySelector('#pf');form.onsubmit=async e=>{e.preventDefault();if(form.querySelector('.edit-lock-notice'))return;let d=Object.fromEntries(new FormData(form));A.forEach(([k])=>d[k]=Math.max(0,Math.min(300,Number(d[k]||0))));let save=form.querySelector('button');save.disabled=true;try{await api(id?'/api/players/'+id:'/api/players',{method:id?'PUT':'POST',body:JSON.stringify(d)});msg('Saved.');adminTab('players')}catch(x){if(x.status===423){showEditLock(form)}else{msg(x.message);save.disabled=false}}};
 if(id){let busy=false;let timer=setInterval(async()=>{if(!form.isConnected){clearInterval(timer);return}if(busy)return;busy=true;try{let {player:p}=await api('/api/players/'+encodeURIComponent(id));if(form.isConnected&&p.locked){showEditLock(form);clearInterval(timer)}}catch{}finally{busy=false}},3000)}
}
async function edit(id){let version=++adminViewVersion;try{let {player:p}=await api('/api/players/'+encodeURIComponent(id));if(version!==adminViewVersion||!document.querySelector('#adminContent'))return;if(p.locked){msg('This player is locked. Unlock it before editing.');await adminTab('players');return}selectAdminTab('players');document.querySelector('#adminContent').innerHTML=form(p);wireForm(id)}catch(e){msg(e.message)}}
async function del(id){if(!confirm('Delete this player and assessment history?'))return;try{await api('/api/players/'+id,{method:'DELETE'});msg('Deleted.');adminTab('players')}catch(e){msg(e.message)}}
async function lock(id,locked){if(locked){settings(id);return}try{await api('/api/players/'+id+'/lock',{method:'POST'});msg('Locked.');adminTab('players')}catch(e){msg(e.message)}}
async function settings(selectId){selectAdminTab('settings');let c=document.querySelector('#adminContent'),version=++adminViewVersion;c.innerHTML=`<section class="card"><h2>Personal settings</h2><div class="notice">Unlocking is deliberately a separate action. Entering the admin area does not unlock records.</div><div style="max-width:520px;margin-top:20px"><h3>Unlock player</h3><p>Enter your personal account code.</p><select id="u"></select>${codeHTML('unlock')}<div id="ue" class="error"></div><button id="ub" style="width:100%">Verify & unlock</button></div></section>`;wireCodes(c);let players;try{({players}=await api('/api/players'))}catch(e){if(version===adminViewVersion&&c.isConnected)c.querySelector('#ue').textContent=e.message;return}if(version!==adminViewVersion||!c.isConnected)return;let locked=players.filter(p=>p.locked);document.querySelector('#u').innerHTML=locked.length?locked.map(p=>`<option value="${p.id}">${esc(p.name)} - Assessment: ${date(p.assessed_at)}</option>`).join(''):'<option value="">No locked players</option>';document.querySelector('#ub').disabled=!locked.length;if(selectId)document.querySelector('#u').value=selectId;document.querySelector('#ub').onclick=async()=>{let id=document.querySelector('#u').value,c=getCode('unlock');if(!/^\d{6}$/.test(c)){document.querySelector('#ue').textContent='Enter all six digits.';return}try{await api('/api/players/'+id+'/unlock',{method:'POST',body:JSON.stringify({code:c})});msg('Unlocked.');settings()}catch(e){document.querySelector('#ue').textContent=e.message}}}
function setupLink(account){let url=new URL(location.href);url.hash='/setup?'+new URLSearchParams({account:account.id,invite:account.invitation}).toString();return url.href}
async function openSetupLink(fragment){let params=new URLSearchParams(fragment.split('?')[1]||''),id=params.get('account'),invite=params.get('invite');history.replaceState(null,'',location.pathname+location.search+'#/admin');try{let {accounts:a}=await api('/api/accounts'),account=a.find(x=>x.id===id);if(!account||!invite||account.code_ready||!(account.invitation_expires_at>Date.now())){render('<div class="login"><h1>Setup link unavailable</h1><p>This invitation expired or the account is already set up. Ask the primary admin for help.</p><button id="setupBack">Choose an account</button></div>');document.querySelector('#setupBack').onclick=accounts;return}login(account,invite)}catch(e){render(`<div class="login"><h1>Setup unavailable</h1><p class="error">${esc(e.message)}</p><button id="setupRetry">Retry</button></div>`);document.querySelector('#setupRetry').onclick=()=>openSetupLink(fragment)}}
async function copySetupValue(button,value){const label=button.dataset.copyLabel||button.textContent;button.dataset.copyLabel=label;button.style.width=button.getBoundingClientRect().width+'px';clearTimeout(button.copyTimer);try{await navigator.clipboard.writeText(value);button.textContent='Copied \u2713';button.setAttribute('aria-label',label+' copied');button.copyTimer=setTimeout(()=>{if(button.isConnected){button.textContent=label;button.removeAttribute('aria-label')}},2000)}catch{let input=document.createElement('input');input.value=value;input.readOnly=true;input.setAttribute('aria-label','Select and copy');button.closest('.invitation-details').append(input);input.focus();input.select();msg('Copy the selected text.')}}
function route(){let h=location.hash||'#/';if(h.startsWith('#/setup?')){openSetupLink(h);return}if(h==='#/'||h==='#')home();else if(h==='#/admin')admin();else if(h.startsWith('#/player/'))player(decodeURIComponent(h.split('/')[2]))}addEventListener('hashchange',route);route();

async function accounts(){try{let {accounts:a}=await api('/api/accounts');render(`<div class="login"><h1>Accounts</h1><p>Select an account to sign in with its personal code.</p><section class="card">${a.map(x=>`<div class="listrow"><div><strong>${esc(x.name)}</strong><div class="meta">${x.is_primary?'Primary administrator':'Administrator'}${x.code_ready?'':' - Setup required'}</div></div><button data-account="${esc(x.id)}">Sign in</button></div>`).join('')}</section></div>`);V.querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>login(a.find(x=>x.id===b.dataset.account)))}catch(e){render(`<div class="login"><h1>Accounts unavailable</h1><p class="error">${esc(e.message)}</p><button id="retryAccounts">Retry</button></div>`);document.querySelector('#retryAccounts').onclick=accounts}}
let invitationTimer;
async function manageAccounts(){
 clearInterval(invitationTimer);let c=document.querySelector('#adminContent'),version=++adminViewVersion;
 try{
 let {accounts:a}=await api('/api/accounts');if(version!==adminViewVersion||!c.isConnected)return;
 c.innerHTML=`<section class="card" id="managedAccounts"><h2>Admin accounts</h2><form id="af" class="toolbar"><input name="name" aria-label="Administrator name" placeholder="Administrator name" maxlength="60" required><button>Add account</button></form>${a.map(x=>`<div class="listrow"><div><strong>${esc(x.name)}</strong>${x.is_primary?'<div class="meta">Primary administrator. Can manage admin accounts.</div>':''}${x.invitation?`<div class="invitation-details" data-expires="${Number(x.invitation_expires_at)}"><p>Send this to <strong>${esc(x.name)}</strong> to choose a personal sign-in code.</p><div class="toolbar"><input readonly aria-label="Setup invitation for ${esc(x.name)}" value="${esc(x.invitation)}"><button class="secondary" data-copy-invite="${esc(x.id)}">Copy code</button></div><button class="secondary" data-copy-link="${esc(x.id)}">Copy setup link</button><div class="meta invitation-expiry">Expires ${esc(new Date(x.invitation_expires_at).toLocaleString())} - <span class="invite-countdown"></span></div></div>`:''}</div>${x.is_primary?`<div class="actions">${accountOptions(x)}</div>`:`<div class="actions">${!x.code_ready?`<button data-invite="${esc(x.id)}">${x.invitation?'Regenerate setup invitation':'Generate setup invitation'}</button>`:`<button class="secondary" data-reset-code="${esc(x.id)}">Reset sign-in code</button>`}${accountOptions(x)}</div>`}</div>`).join('')}</section>`;
 document.querySelector('#af').onsubmit=async e=>{e.preventDefault();try{await api('/api/accounts',{method:'POST',body:JSON.stringify({name:new FormData(e.target).get('name')})});await manageAccounts()}catch(e){msg(e.message)}};
 c.querySelectorAll('[data-copy-invite],[data-copy-link]').forEach(b=>b.onclick=async()=>{let account=a.find(x=>x.id===(b.dataset.copyInvite||b.dataset.copyLink));if(Date.now()>=account.invitation_expires_at){await manageAccounts();return}await copySetupValue(b,b.hasAttribute('data-copy-link')?setupLink(account):account.invitation)});
 c.querySelectorAll('[data-invite]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/accounts/invite',{method:'POST',body:JSON.stringify({account_id:b.dataset.invite})});await manageAccounts()}catch(e){msg(e.message);b.disabled=false}});
 c.querySelectorAll('[data-reset-code]').forEach(b=>b.onclick=async()=>{let account=a.find(x=>x.id===b.dataset.resetCode);if(!confirm(`Reset the sign-in code for ${account.name}? This signs them out and creates a new setup invitation.`))return;b.disabled=true;try{await api('/api/accounts/reset-code',{method:'POST',body:JSON.stringify({account_id:account.id})});await manageAccounts()}catch(e){msg(e.message);b.disabled=false}});
 c.querySelectorAll('[data-stats]').forEach(b=>b.onclick=()=>showAccountStatistics(b.dataset.stats,b));
 c.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{let account=a.find(x=>x.id===b.dataset.delete);b.closest('details').open=false;if(!confirm(`Delete the administrator account ${account.name}?`))return;try{await api('/api/accounts/'+encodeURIComponent(b.dataset.delete),{method:'DELETE'});await manageAccounts()}catch(e){msg(e.message)}});
 const panel=document.querySelector('#managedAccounts');
 function tick(){if(!panel.isConnected){clearInterval(invitationTimer);return}let expired=false;panel.querySelectorAll('[data-expires]').forEach(el=>{let seconds=Math.max(0,Math.ceil((Number(el.dataset.expires)-Date.now())/1000));el.querySelector('.invite-countdown').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} remaining`;if(!seconds)expired=true});if(expired){clearInterval(invitationTimer);manageAccounts()}}
 tick();invitationTimer=setInterval(tick,1000);
 }catch(e){msg(e.message)}
}
function logRow(l){let verbs={created_player:'created player',updated_player:'updated player',deleted_player:'deleted player',locked_player:'locked player',unlocked_player:'unlocked player',created_admin:'created admin account',deleted_admin:'deleted admin account',reset_admin_code:'reset the sign-in code for admin account',set_admin_code:'set up a personal sign-in code for admin account',generated_admin_invitation:'generated a one-time setup invitation for admin account'};return `<div class="listrow"><div>${esc(l.actor_name)} ${esc(verbs[l.action]||l.action)} <strong>${esc(l.player_name??l.account_name)}</strong>${l.player_name!==null?`<div class="meta">Assessment: ${date(l.assessed_at)} - Reference #${Number(l.assessment_id)}</div>`:''}<div class="meta">${esc(new Date(l.created_at).toLocaleString())}</div></div></div>`}
async function logs(){
 let c=document.querySelector('#adminContent');c.innerHTML=`<section class="card" id="logsPanel"><h2>Activity logs</h2><form id="logFilters" class="log-filters"><div class="field"><label for="logFrom">From date</label><input id="logFrom" type="date"></div><div class="field"><label for="logTo">To date</label><input id="logTo" type="date"></div><div class="field"><label for="logAction">Action</label><select id="logAction"><option value="">All actions</option></select></div><div class="field"><label for="logAdmin">Administrator</label><select id="logAdmin"><option value="">All administrators</option></select></div><div class="field"><label for="logSize">Logs per page</label><select id="logSize">${[10,25,50,100].map(n=>`<option ${n===25?'selected':''}>${n}</option>`).join('')}</select></div><div class="log-filter-actions"><button type="submit">Apply filters</button><button type="button" class="secondary" id="logClear">Clear</button></div></form><p class="meta">Newest first. Dates use your local time.</p><div id="logError" class="error" role="status"></div><div id="lr"></div><div class="log-pagination"><button id="logPrev" class="secondary">Previous</button><span id="logPage" class="meta" aria-live="polite"></span><button id="logNext" class="secondary">Next</button></div></section>`;
 const panel=document.querySelector('#logsPanel'),filters=document.querySelector('#logFilters'),prev=document.querySelector('#logPrev'),next=document.querySelector('#logNext'),error=document.querySelector('#logError');let page=logViewState.page,request=0,applied={...logViewState.filters},metadataLoaded=false;
 const actionLabels={created_player:'Player created',updated_player:'Player updated',deleted_player:'Player deleted',locked_player:'Player locked',unlocked_player:'Player unlocked',created_admin:'Admin created',deleted_admin:'Admin deleted',reset_admin_code:'Sign-in code reset',set_admin_code:'Personal code set up',generated_admin_invitation:'Setup invitation generated'};
 function readFilters(){let from=document.querySelector('#logFrom').value,to=document.querySelector('#logTo').value;if(from&&to&&from>to)throw Error('From date must be before or equal to To date.');let values={limit:document.querySelector('#logSize').value,action:document.querySelector('#logAction').value,administrator:document.querySelector('#logAdmin').value,from,to};if(from)values.start=new Date(from+'T00:00:00').toISOString();if(to){let end=new Date(to+'T00:00:00');end.setDate(end.getDate()+1);values.end=end.toISOString()}return values}
 async function load(target=1){logViewState={page:target,filters:{...applied}};let seq=++request;prev.disabled=next.disabled=true;error.textContent='';panel.setAttribute('aria-busy','true');try{let params=new URLSearchParams({page:target});Object.entries(applied).forEach(([k,v])=>{if(v)params.set(k,v)});let result=await api('/api/logs?'+params);if(!panel.isConnected||seq!==request)return;page=result.page;logViewState={page,filters:{...applied}};document.querySelector('#lr').innerHTML=result.logs.map(logRow).join('')||'<p>No logs match these filters.</p>';let first=result.total?(page-1)*result.page_size+1:0,last=result.total?Math.min(page*result.page_size,result.total):0;document.querySelector('#logPage').textContent=`Page ${page} of ${result.total_pages} - ${first}-${last} of ${result.total} logs`;prev.disabled=page<=1;next.disabled=page>=result.total_pages;
 if(!metadataLoaded){document.querySelector('#logAction').innerHTML='<option value="">All actions</option>'+result.actions.map(action=>`<option value="${esc(action)}">${esc(actionLabels[action]||action.replaceAll('_',' '))}</option>`).join('');document.querySelector('#logAdmin').innerHTML='<option value="">All administrators</option>'+result.administrators.map(actor=>`<option value="${esc(actor.id)}">${esc(actor.name)}</option>`).join('');document.querySelector('#logAction').value=applied.action||'';document.querySelector('#logAdmin').value=applied.administrator||'';metadataLoaded=true}
 }catch(e){if(panel.isConnected&&seq===request){error.textContent=e.message;prev.disabled=next.disabled=true}}finally{if(panel.isConnected&&seq===request)panel.removeAttribute('aria-busy')}}
 filters.onsubmit=e=>{e.preventDefault();try{applied=readFilters();load(1)}catch(e){error.textContent=e.message}};
 document.querySelector('#logSize').onchange=()=>{try{applied=readFilters();load(1)}catch(e){error.textContent=e.message}};
 document.querySelector('#logClear').onclick=()=>{filters.reset();applied=readFilters();load(1)};
 prev.onclick=()=>load(page-1);next.onclick=()=>load(page+1);document.querySelector('#logFrom').value=applied.from||'';document.querySelector('#logTo').value=applied.to||'';document.querySelector('#logSize').value=applied.limit||'25';await load(page);
}

// Move the header pixel-for-pixel through the first header-height of scrolling.
(function setupScrollHeader(){
 const header=document.querySelector('header'),scroller=document.querySelector('#scrollArea');
 if(!header||!scroller)return;
 let height=0;
 function update(){
  const offset=Math.min(height,Math.max(0,scroller.scrollTop));
  document.documentElement.style.setProperty('--header-offset',offset+'px');
  header.inert=height>0&&offset>=height;
 }
 function measure(){height=header.getBoundingClientRect().height;update();}
 measure();new ResizeObserver(measure).observe(header);
 scroller.addEventListener('scroll',update,{passive:true});
})();

// Close account options when clicking elsewhere or pressing Escape.
document.addEventListener('click',e=>{document.querySelectorAll('.account-options[open]').forEach(menu=>{if(!menu.contains(e.target))menu.open=false})});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.account-options[open]').forEach(menu=>{menu.open=false;menu.querySelector('summary').focus()})});

function accountOptions(account){return `<details class="account-options"><summary aria-label="Account options for ${esc(account.name)}" title="Account options">&#8942;</summary><div class="account-options-panel"><button class="secondary" data-stats="${esc(account.id)}">Account statistics</button>${account.is_primary?'':`<button class="danger" data-delete="${esc(account.id)}">Delete account</button>`}</div></details>`}
async function showAccountStatistics(id,trigger){trigger.closest('details').open=false;let dialog=document.createElement('dialog');dialog.className='account-statistics';dialog.setAttribute('aria-label','Account statistics');dialog.innerHTML='<p>Loading account statistics...</p><button data-close-stats>Close</button>';document.body.append(dialog);function wireClose(){dialog.querySelector('[data-close-stats]').onclick=()=>dialog.close()}wireClose();dialog.addEventListener('close',()=>{dialog.remove();if(trigger.isConnected)trigger.closest('details').querySelector('summary').focus()});dialog.addEventListener('click',e=>{if(e.target===dialog){let r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.showModal();try{let {account,statistics:s}=await api('/api/accounts/'+encodeURIComponent(id)+'/stats');if(!dialog.isConnected)return;let created=account.created_at,age=created?Math.max(0,Math.floor((Date.now()-new Date(created).getTime())/86400000)):null;let labels=[['Actions performed',s.actions_performed],['Actions by others affecting this account',s.actions_received],['Distinct players assessed',s.players_assessed],['Assessments saved',s.assessments_saved],['Players created',s.players_created],['Player updates',s.player_updates],['Player locks',s.players_locked],['Player unlocks',s.players_unlocked],['Code resets received',s.code_resets_received],['Setup invitations received',s.invitations_received]];dialog.innerHTML=`<h2>${esc(account.name)} - Account statistics</h2><p>${created?`Created ${esc(new Date(created).toLocaleString())} (${age} ${age===1?'day':'days'} old).`:'Account creation date was not recorded.'}</p><div class="account-stat-grid">${labels.map(([label,value])=>`<div class="stat"><b>${Number(value||0)}</b><span>${label}</span></div>`).join('')}</div><p class="meta">First recorded action: ${s.first_activity?esc(new Date(s.first_activity).toLocaleString()):'None'}<br>Latest recorded action: ${s.last_activity?esc(new Date(s.last_activity).toLocaleString()):'None'}</p><p class="meta">Counts cover recorded logs only. Each successful player creation or update counts as an assessment saved. Actions affecting the account count actions performed by other admins.</p><button data-close-stats>Close</button>`;wireClose()}catch(e){if(dialog.isConnected){dialog.innerHTML=`<h2>Statistics unavailable</h2><p class="error">${esc(e.message)}</p><button data-close-stats>Close</button>`;wireClose()}}}
