const API=(window.APP_CONFIG?.API_URL||'').replace(/\/$/,''),V=document.querySelector('#view'),T=document.querySelector('#toast');
const A=[['control','CTRL','Control'],['execution','EXEC','Execution'],['defending','DEF','Defending'],['reaction_time','RT','Reaction Time'],['chemistry','CHEM','Chemistry'],['game_sense','GS','Game Sense']];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tier=n=>n>=257?'S':n>=215?'A':n>=172?'B':n>=129?'C':n>=86?'D':n>=43?'E':'F';
const date=x=>x?new Date(x).toLocaleDateString(undefined,{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
function codeHTML(id='code'){return `<div class="code" data-code="${id}">${[0,1,2,3,4,5].map(i=>`<input maxlength="1" inputmode="numeric" aria-label="Digit ${i+1}">`).join('')}</div>`}
function wireCodes(root=V){root.querySelectorAll('.code').forEach(b=>{let a=[...b.querySelectorAll('input')];a.forEach((x,i)=>{x.oninput=()=>{x.value=x.value.replace(/\D/g,'').slice(-1);if(x.value)a[i+1]?.focus()};x.onkeydown=e=>{if(e.key==='Backspace'&&!x.value)a[i-1]?.focus()};x.onpaste=e=>{e.preventDefault();let s=e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6);if(!s)return;a.forEach((input,j)=>input.value=s[j]||'');a[Math.min(s.length,5)]?.focus()}})})}
function getCode(id='code'){return [...V.querySelector(`[data-code="${id}"]`).querySelectorAll('input')].map(x=>x.value).join('')}
// A tab-scoped token also supports browsers that block cross-site cookies.
let sessionToken='';try{sessionToken=sessionStorage.getItem('admin_session_token')||''}catch{}
function saveSessionToken(token){sessionToken=token||'';try{if(sessionToken)sessionStorage.setItem('admin_session_token',sessionToken);else sessionStorage.removeItem('admin_session_token')}catch{}}
async function api(path,opt={}){if(!API||API.includes('REPLACE-WITH'))throw Error('Set API_URL in config.js first.');let r=await fetch(API+path,{...opt,credentials:'include',headers:{'Content-Type':'application/json',...(sessionToken?{Authorization:'Bearer '+sessionToken}:{}),...(opt.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok){let error=Error(d.error||`Request failed (${r.status})`);error.status=r.status;throw error}if(path==='/api/login'&&d.session_token)saveSessionToken(d.session_token);if(path==='/api/logout')saveSessionToken('');return d}

function render(s){V.innerHTML=s;wireCodes();}
function msg(s){T.textContent=s;T.classList.add('show');setTimeout(()=>T.classList.remove('show'),2300)}
async function home(){try{let {players}=await api('/api/players');render(`<div class="hero"><div class="eyebrow">PLAYER DATABASE</div><h1>Players</h1><p>Current ratings, classes and development records.</p></div><div class="toolbar"><input id="q" placeholder="Search players or classes…"></div><div id="cards" class="grid"></div>`);let draw=()=>{let q=document.querySelector('#q').value.toLowerCase(),p=players.filter(x=>(x.name+' '+x.class_name).toLowerCase().includes(q));document.querySelector('#cards').innerHTML=p.length?p.map(card).join(''):`<div class="empty" style="grid-column:1/-1">No players found.</div>`};document.querySelector('#q').oninput=draw;draw()}catch(e){render(`<div class="empty">${esc(e.message)}</div>`)}}
function card(p){return `<a class="player-card" href="#/player/${encodeURIComponent(p.id)}"><div class="card card-surface"><div class="player-head"><div><div class="name">${esc(p.name)}</div><div class="class">${esc(p.class_name||'Class undetermined')}${p.locked?' · LOCKED':''}</div></div><span class="badge ${p.overall_tier}">${p.overall_tier}</span></div>${A.map(([k,s])=>`<div class="barrow"><span>${s}</span><div class="bar"><i style="width:${Math.min(100,(p[k]||0)/3)}%"></i></div><b>${tier(p[k])}</b></div>`).join('')}<div class="meta">${A.reduce((n,[k])=>n+Number(p[k]||0),0)} / 1800 · ${date(p.assessed_at)}</div></div></a>`}
async function player(id){try{let {player:p,history}=await api('/api/players/'+encodeURIComponent(id)),sum=A.reduce((n,[k])=>n+Number(p[k]||0),0);render(`<a href="#/" class="meta">← All players</a><div class="hero" style="margin-top:20px"><div class="eyebrow">PLAYER PROFILE</div><h1>${esc(p.name)}</h1><p>${esc(p.class_name||'Class undetermined')} · Overall <b>${esc(p.overall_tier)}</b></p></div><div class="two"><section class="card"><h2>Attributes</h2><table class="table"><tr><th>Attribute</th><th>Points</th><th>Tier</th></tr>${A.map(([k,,n])=>`<tr><td>${n}</td><td>${p[k]} / 300</td><td><b>${tier(p[k])}</b></td></tr>`).join('')}</table><div class="stats"><div class="stat"><b>${sum}</b><span>Total / 1800</span></div><div class="stat"><b>${(sum/6).toFixed(2)}</b><span>Average / 300</span></div><div class="stat"><b>${tier(sum/6)}</b><span>Attribute Tier</span></div></div></section><aside><section class="card"><h2>Playstyle</h2><p>${esc(p.playstyle||'No description recorded.')}</p><h3>Strengths</h3><p>${esc(p.strengths||'—')}</p><h3>Weaknesses</h3><p>${esc(p.weaknesses||'—')}</p></section><section class="card" style="margin-top:15px"><h2>Assessment History</h2>${history.length?history.slice().reverse().map(h=>`<div class="listrow"><div><b>${date(h.assessed_at)}</b><div class="meta">${h.total} / 1800 · Overall ${h.overall_tier}</div></div></div>`).join(''):'<p>No history.</p>'}</section></aside></div>`)}catch(e){render(`<div class="empty">${esc(e.message)}</div>`)}}
function login(account){if(!account)return accounts();let invitation=!account.code_ready&&!account.is_primary;render(`<div class="login"><h1>Sign in</h1><p>Access <strong>${esc(account.name)}</strong> with ${account.code_ready?'your personal code':invitation?'your one-time setup invitation':'the existing admin code to set up your account'}.</p><section class="card">${invitation?'<input id="invitation" aria-label="Setup invitation" placeholder="Setup invitation" autocomplete="off">':codeHTML()}<div id="err" class="error"></div><div class="login-actions"><button id="go">Continue</button><button id="chooseAccount" class="secondary">Choose another account</button></div></section></div>`);document.querySelector('#chooseAccount').onclick=accounts;document.querySelector('#go').onclick=async()=>{let code=invitation?document.querySelector('#invitation').value.trim():getCode();let button=document.querySelector('#go');button.disabled=true;try{let result=await api('/api/login',{method:'POST',body:JSON.stringify({code,account_id:account.id})});if(result.setup_required)setupPersonalCode(account,code);else await admin()}catch(e){document.querySelector('#err').textContent=e.message}finally{button.disabled=false}}}
function setupPersonalCode(account,setupCode){render(`<div class="login"><h1>Create your code</h1><p>Choose a personal six-digit code for <strong>${esc(account.name)}</strong>.</p><section class="card"><h2>New code</h2>${codeHTML('newCode')}<h2>Confirm code</h2>${codeHTML('confirmCode')}<div id="err" class="error"></div><button id="saveCode">Save and sign in</button><button id="cancelCode" class="secondary">Cancel</button></section></div>`);V.querySelectorAll('.code input').forEach(x=>x.type='password');document.querySelector('#cancelCode').onclick=accounts;document.querySelector('#saveCode').onclick=async()=>{let new_code=getCode('newCode'),confirm_code=getCode('confirmCode');if(!/^\d{6}$/.test(new_code)||new_code!==confirm_code){document.querySelector('#err').textContent='Enter and confirm the same six-digit code.';return}let button=document.querySelector('#saveCode');button.disabled=true;try{await api('/api/login',{method:'POST',body:JSON.stringify({account_id:account.id,code:setupCode,new_code,confirm_code})});await admin()}catch(e){document.querySelector('#err').textContent=e.message}finally{button.disabled=false}}}

async function admin(){try{let s=await api('/api/session');if(!s.authenticated)return accounts();render(`<div class="admin"><div class="hero"><div class="eyebrow">ADMINISTRATOR</div><h1>Manage database</h1><p>Signed in as <strong>${esc(s.account.name)}</strong>.</p></div><div class="tabs"><button data-tab="players">Players</button><button data-tab="new">New Player</button><button data-tab="settings">Settings</button><button data-tab="logs">Logs</button>${s.account.is_primary?'<button data-tab="accounts">Manage Accounts</button>':''}<button id="switch" class="secondary">Switch account</button><button class="secondary" id="out">Sign out</button></div><div id="adminContent"></div></div>`);document.querySelector('#switch').onclick=()=>accounts();document.querySelector('#out').onclick=async()=>{await api('/api/logout',{method:'POST'});location.hash='#/';home()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>adminTab(b.dataset.tab));adminTab('players')}catch(e){login()}}
async function adminTab(tab){let c=document.querySelector('#adminContent');if(tab==='logs'){logs();return}if(tab==='accounts'){manageAccounts();return}if(tab==='new'){c.innerHTML=form();wireForm();return}if(tab==='settings'){settings();return}try{let {players}=await api('/api/players');c.innerHTML=`<section class="card">${players.length?players.map(p=>`<div class="listrow"><div><b>${esc(p.name)}</b><div class="meta">${esc(p.class_name||'Class undetermined')} · ${p.overall_tier}${p.locked?' · LOCKED':''}</div></div><div class="actions"><button class="secondary" onclick="edit('${p.id}')">Edit</button><button class="secondary" onclick="lock('${p.id}',${!!p.locked})">${p.locked?'Unlock':'Lock'}</button><button class="danger" onclick="del('${p.id}')">Delete</button></div></div>`).join(''):'<p>No players yet.</p>'}</section>`}catch(e){c.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function field(n,l,v='',type='text',full=false){return `<div class="field ${full?'full':''}"><label>${l}</label>${full?`<textarea name="${n}">${esc(v)}</textarea>`:`<input name="${n}" type="${type}" value="${esc(v)}" ${type==='number'?'min="0" max="300"':''}>`}</div>`}
function form(p={}){return `<section class="card"><h2>${p.id?'Edit':'New'} Player</h2><form id="pf"><div class="formgrid">${field('name','Player name',p.name||'')} ${field('class_name','Class',p.class_name||'')}${A.map(([k,,n])=>field(k,n,p[k]??0,'number')).join('')}${field('overall_tier','Overall tier',p.overall_tier||'B')}${field('assessed_at','Assessment date',p.assessed_at?String(p.assessed_at).slice(0,10):new Date().toISOString().slice(0,10),'date')}${field('playstyle','Playstyle',p.playstyle||'','text',true)}${field('strengths','Strengths',p.strengths||'','text',true)}${field('weaknesses','Weaknesses',p.weaknesses||'','text',true)}</div><div style="text-align:right;margin-top:16px"><button>Save</button></div></form></section>`}
function wireForm(id=null){document.querySelector('#pf').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));A.forEach(([k])=>d[k]=Math.max(0,Math.min(300,Number(d[k]||0))));try{await api(id?'/api/players/'+id:'/api/players',{method:id?'PUT':'POST',body:JSON.stringify(d)});msg('Saved.');adminTab('players')}catch(x){msg(x.message)}}}
async function edit(id){let {player:p}=await api('/api/players/'+id);document.querySelector('#adminContent').innerHTML=form(p);wireForm(id)}
async function del(id){if(!confirm('Delete this player and assessment history?'))return;try{await api('/api/players/'+id,{method:'DELETE'});msg('Deleted.');adminTab('players')}catch(e){msg(e.message)}}
async function lock(id,locked){if(locked){settings(id);return}try{await api('/api/players/'+id+'/lock',{method:'POST'});msg('Locked.');adminTab('players')}catch(e){msg(e.message)}}
async function settings(selectId){let c=document.querySelector('#adminContent');c.innerHTML=`<section class="card"><h2>Personal settings</h2><div class="notice">Unlocking is deliberately a separate action. Entering the admin area does not unlock records.</div><div style="max-width:520px;margin-top:20px"><h3>Unlock player</h3><p>Enter your personal account code.</p><select id="u"></select>${codeHTML('unlock')}<div id="ue" class="error"></div><button id="ub" style="width:100%">Verify & unlock</button></div></section>`;wireCodes(c);let {players}=await api('/api/players');let locked=players.filter(p=>p.locked);document.querySelector('#u').innerHTML=locked.length?locked.map(p=>`<option value="${p.id}">${esc(p.name)} ? ${date(p.assessed_at)}</option>`).join(''):'<option value="">No locked players</option>';if(selectId)document.querySelector('#u').value=selectId;document.querySelector('#ub').onclick=async()=>{let id=document.querySelector('#u').value,c=getCode('unlock');if(!/^\d{6}$/.test(c)){document.querySelector('#ue').textContent='Enter all six digits.';return}try{await api('/api/players/'+id+'/unlock',{method:'POST',body:JSON.stringify({code:c})});msg('Unlocked.');settings()}catch(e){document.querySelector('#ue').textContent=e.message}}}
function route(){let h=location.hash||'#/';if(h==='#/'||h==='#')home();else if(h==='#/admin')admin();else if(h.startsWith('#/player/'))player(decodeURIComponent(h.split('/')[2]))}addEventListener('hashchange',route);route();

async function accounts(){try{let {accounts:a}=await api('/api/accounts');render(`<div class="login"><h1>Accounts</h1><p>Select an account to sign in with its personal code.</p><section class="card">${a.map(x=>`<div class="listrow"><div><strong>${esc(x.name)}</strong><div class="meta">${x.is_primary?'Primary administrator':'Administrator'}${x.code_ready?'':' ? Setup required'}</div></div><button data-account="${esc(x.id)}">Sign in</button></div>`).join('')}</section></div>`);V.querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>login(a.find(x=>x.id===b.dataset.account)))}catch(e){render(`<div class="login"><h1>Accounts unavailable</h1><p class="error">${esc(e.message)}</p><button id="retryAccounts">Retry</button></div>`);document.querySelector('#retryAccounts').onclick=accounts}}
function showInvitation(invitation){let c=document.querySelector('#adminContent');let section=document.createElement('section');section.className='card';section.innerHTML=`<h2>One-time setup invitation</h2><p>Share this privately with the account owner. They will use it once to create their personal code.</p><input readonly aria-label="Setup invitation" value="${esc(invitation)}">`;c.prepend(section);section.querySelector('input').onclick=e=>e.target.select()}
async function manageAccounts(){let c=document.querySelector('#adminContent');try{let {accounts:a}=await api('/api/accounts');c.innerHTML=`<section class="card"><h2>Admin accounts</h2><form id="af" class="toolbar"><input name="name" aria-label="Administrator name" placeholder="Administrator name" maxlength="60" required><button>Add account</button></form>${a.map(x=>`<div class="listrow"><strong>${esc(x.name)}</strong>${x.is_primary?'Primary administrator ? Protected':`<div class="actions">${!x.code_ready?`<button data-invite="${esc(x.id)}">Create setup invitation</button>`:`<button class="secondary" data-reset-code="${esc(x.id)}">Reset sign-in code</button>`}<button class="danger" data-delete="${esc(x.id)}">Delete</button></div>`}</div>`).join('')}</section>`;document.querySelector('#af').onsubmit=async e=>{e.preventDefault();try{let result=await api('/api/accounts',{method:'POST',body:JSON.stringify({name:new FormData(e.target).get('name')})});await manageAccounts();showInvitation(result.invitation)}catch(e){msg(e.message)}};c.querySelectorAll('[data-invite]').forEach(b=>b.onclick=async()=>{try{let result=await api('/api/accounts/invite',{method:'POST',body:JSON.stringify({account_id:b.dataset.invite})});showInvitation(result.invitation)}catch(e){msg(e.message)}});c.querySelectorAll('[data-reset-code]').forEach(b=>b.onclick=async()=>{let account=a.find(x=>x.id===b.dataset.resetCode);if(!confirm(`Reset the sign-in code for ${account.name}? This signs them out and they will need a new setup invitation.`))return;b.disabled=true;try{let result=await api('/api/accounts/reset-code',{method:'POST',body:JSON.stringify({account_id:account.id})});await manageAccounts();showInvitation(result.invitation)}catch(e){msg(e.message);b.disabled=false}});c.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this administrator account?'))return;try{await api('/api/accounts/'+encodeURIComponent(b.dataset.delete),{method:'DELETE'});manageAccounts()}catch(e){msg(e.message)}})}catch(e){msg(e.message)}}
function logRow(l){let verbs={created_player:'created player',updated_player:'updated player',deleted_player:'deleted player',locked_player:'locked player',unlocked_player:'unlocked player',created_admin:'created admin account',deleted_admin:'deleted admin account',reset_admin_code:'reset the sign-in code for admin account'};return `<div class="listrow"><div>${esc(l.actor_name)} ${esc(verbs[l.action]||l.action)} <strong>${esc(l.player_name??l.account_name)}</strong>${l.player_name!==null?`<div class="meta">Assessment: ${date(l.assessed_at)} ? Reference #${Number(l.assessment_id)}</div>`:''}<div class="meta">${esc(new Date(l.created_at).toLocaleString())}</div></div></div>`}
async function logs(){let c=document.querySelector('#adminContent');c.innerHTML='<section class="card"><h2>Activity logs</h2><div id="lr"></div><button id="lm" class="secondary">Load older logs</button></section>';let before='',button=document.querySelector('#lm');async function load(){button.disabled=true;try{let {logs:l}=await api('/api/logs'+(before?'?before='+before:''));document.querySelector('#lr').insertAdjacentHTML('beforeend',l.map(logRow).join('')||(!before?'<p>No activity recorded yet.</p>':''));before=l.at(-1)?.id||before;button.hidden=l.length<100}catch(e){msg(e.message)}finally{button.disabled=false}}button.onclick=load;await load()}

// Move the header pixel-for-pixel through the first header-height of scrolling.
(function setupScrollHeader(){
 const header=document.querySelector('header'),scroller=document.querySelector('#scrollArea');
 if(!header||!scroller)return;
 let height=0;
 function update(){
  const offset=Math.min(height,Math.max(0,scroller.scrollTop));
  document.documentElement.style.setProperty('--header-offset',offset+'px');
  header.inert=height>0&&offset>=height;
 }
 function measure(){height=header.getBoundingClientRect().height;update();}
 measure();new ResizeObserver(measure).observe(header);
 scroller.addEventListener('scroll',update,{passive:true});
})();
