const H=(origin,env)=>({'Content-Type':'application/json','Access-Control-Allow-Origin':env.ALLOWED_ORIGIN||origin,'Access-Control-Allow-Credentials':'true','Vary':'Origin','Cache-Control':'no-store'});
const J=(d,s,o,e)=>new Response(JSON.stringify(d),{status:s,headers:H(o,e)});const A=['control','execution','defending','reaction_time','chemistry','game_sense'];
const now=()=>new Date().toISOString();const uuid=()=>crypto.randomUUID();
async function hash(s){let h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function codeHash(code,salt){let key=await crypto.subtle.importKey('raw',new TextEncoder().encode(code),'PBKDF2',false,['deriveBits']);let bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:100000},key,256);return [...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function credential(e,id){return e.DB.prepare('SELECT * FROM admin_credentials WHERE account_id=?').bind(id).first()}
function saveInvitation(e,id,token,expires){return e.DB.prepare('INSERT INTO admin_invitations(account_id,token,expires_at) SELECT ?,?,? WHERE NOT EXISTS(SELECT 1 FROM admin_credentials WHERE account_id=? AND code_hash IS NOT NULL) ON CONFLICT(account_id) DO UPDATE SET token=excluded.token,expires_at=excluded.expires_at').bind(id,token,expires,id)}
function cookie(n,v,age){return `${n}=${v}; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=${age}`}
function getCookie(r){return r.headers.get('Authorization')?.match(/^Bearer ([A-Za-z0-9-]+)$/)?.[1]||r.headers.get('Cookie')?.match(/(?:^|; )admin_session=([^;]+)/)?.[1]||null}
async function session(r,e){let t=getCookie(r);if(!t)return null;return e.DB.prepare('SELECT s.token_hash,a.id,a.name,a.is_primary FROM admin_sessions s LEFT JOIN admin_accounts a ON a.id=s.account_id WHERE s.token_hash=? AND s.expires_at>? AND EXISTS(SELECT 1 FROM admin_credentials c WHERE c.account_id=a.id AND c.code_hash IS NOT NULL)').bind(await hash(t),Date.now()).first()}
async function isAuth(r,e){return !!(await session(r,e))?.id}
async function guard(r,e,o){if(!await isAuth(r,e))return J({error:'Select an administrator account first.'},401,o,e)}
function audit(e,user,action,player=null,assessmentId=null,account=null,onlyChanged=false){return e.DB.prepare(`INSERT INTO activity_logs(actor_id,actor_name,action,player_id,player_name,assessed_at,assessment_id,account_name,created_at) ${onlyChanged?'SELECT ':'VALUES('}?,?,?,?,?,?,COALESCE(?,(SELECT MAX(id) FROM assessments WHERE player_id=?)),?,?${onlyChanged?' WHERE changes() > 0':')'}`).bind(user.id,user.name,action,player?.id||null,player?.name||null,player?.assessed_at||null,assessmentId,player?.id||null,account,now())}
function accountAuditAfterChange(e,user,action,accountName){return e.DB.prepare('INSERT INTO activity_logs(actor_id,actor_name,action,account_name,created_at) SELECT ?,?,?,?,? WHERE changes() > 0').bind(user.id,user.name,action,accountName,now())}
async function playerAudit(r,e,action,pl){let user=await session(r,e),assessment=await e.DB.prepare('SELECT id FROM assessments WHERE player_id=? ORDER BY id DESC LIMIT 1').bind(pl.id).first();return audit(e,user,action,pl,assessment?.id||null)}
const total=p=>A.reduce((s,k)=>s+Number(p[k]||0),0);
function valid(p){if(!p.name?.trim())return'Player name is required.';if(!/^[SABCDEF]$/.test(p.overall_tier||''))return'Invalid overall tier.';for(let k of A){let n=Number(p[k]);if(!Number.isInteger(n)||n<0||n>300)return`${k} must be 0–300.`}if(!p.assessed_at)return'Assessment date is required.'}
async function duplicatePlayer(e,name,exceptId=''){return e.DB.prepare('SELECT id FROM players WHERE trim(name) = trim(?) COLLATE NOCASE AND id <> ? LIMIT 1').bind(name,exceptId).first()}
const duplicateNameError='A player with that name already exists. Edit the existing player to add another assessment.';
function snap(e,p,onlyChanged=false){return e.DB.prepare(`INSERT INTO assessments(player_id,assessed_at,overall_tier,control,execution,defending,reaction_time,chemistry,game_sense,total) ${onlyChanged?'SELECT ?,?,?,?,?,?,?,?,?,? WHERE changes() > 0':'VALUES(?,?,?,?,?,?,?,?,?,?)'}`).bind(p.id,p.assessed_at,p.overall_tier,...A.map(k=>Number(p[k])),total(p))}
async function main(r,e){let u=new URL(r.url),o=r.headers.get('Origin')||'',p=u.pathname,m=r.method;
if(m==='OPTIONS')return new Response(null,{status:204,headers:{...H(o,e),'Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization'}});
if(p==='/api/session'){let s=await session(r,e);return J({authenticated:!!s?.id,code_verified:!!s,account:s?.id?{id:s.id,name:s.name,is_primary:!!s.is_primary}:null},200,o,e);}
if(p==='/api/login'&&m==='POST'){
let b=await r.json().catch(()=>({})),id=String(b.account_id||''),code=String(b.code||'');
let account=await e.DB.prepare('SELECT id,name,is_primary FROM admin_accounts WHERE id=?').bind(id).first();if(!account)return J({error:'Invalid account or code.'},401,o,e);
let window=Math.floor(Date.now()/600000);let attempts=await e.DB.prepare('INSERT INTO admin_login_attempts(account_id,window,attempts) VALUES(?,?,1) ON CONFLICT(account_id) DO UPDATE SET window=excluded.window,attempts=CASE WHEN admin_login_attempts.window=excluded.window THEN admin_login_attempts.attempts+1 ELSE 1 END RETURNING attempts').bind(id,window).first();if(attempts.attempts>10)return J({error:'Too many attempts. Try again in ten minutes.'},429,o,e);
let c=await credential(e,id);
if(c?.code_hash){if(!/^\d{6}$/.test(code)||await codeHash(code,c.salt)!==c.code_hash)return J({error:'Invalid account code.'},401,o,e)}
else{
let invite=await e.DB.prepare('SELECT token,expires_at FROM admin_invitations WHERE account_id=? AND expires_at>?').bind(id,Date.now()).first();let allowed=invite?code===invite.token:code===e.ADMIN_CODE;
if(!allowed)return J({error:'Invalid setup code. Ask the primary administrator for an invitation.'},401,o,e);
if(!b.new_code)return J({setup_required:true},200,o,e);
if(!/^\d{6}$/.test(String(b.new_code))||b.new_code!==b.confirm_code)return J({error:'Enter and confirm the same six-digit personal code.'},400,o,e);
let salt=uuid(),digest=await codeHash(b.new_code,salt);
let setupTime=Date.now(),authorization=invite?"EXISTS(SELECT 1 FROM admin_invitations WHERE account_id=? AND token=? AND expires_at>?)":"NOT EXISTS(SELECT 1 FROM admin_invitations WHERE account_id=? AND expires_at>?)";
let authorizationArgs=invite?[id,code,setupTime]:[id,setupTime];
let results=await e.DB.batch([e.DB.prepare(`INSERT INTO admin_credentials(account_id,salt,code_hash) SELECT ?,?,? WHERE ${authorization} ON CONFLICT(account_id) DO UPDATE SET salt=excluded.salt,code_hash=excluded.code_hash,invitation_hash=NULL WHERE admin_credentials.code_hash IS NULL`).bind(id,salt,digest,...authorizationArgs),accountAuditAfterChange(e,account,'set_admin_code',account.name),e.DB.prepare('DELETE FROM admin_invitations WHERE account_id=? AND EXISTS(SELECT 1 FROM admin_credentials WHERE account_id=? AND code_hash IS NOT NULL)').bind(id,id)]);let result=results[0];
if(!result.meta?.changes)return J({error:'Setup invitation expired or changed, or account already set up. Try signing in again.'},409,o,e);
}
let t=uuid()+uuid();await e.DB.prepare('INSERT INTO admin_sessions(token_hash,expires_at,account_id) VALUES(?,?,?)').bind(await hash(t),Date.now()+28800000,id).run();return new Response(JSON.stringify({ok:true,session_token:t}),{headers:{...H(o,e),'Set-Cookie':cookie('admin_session',t,28800)}})}
if(p==='/api/logout'&&m==='POST'){let t=getCookie(r);if(t)await e.DB.prepare('DELETE FROM admin_sessions WHERE token_hash=?').bind(await hash(t)).run();return new Response('{"ok":true}',{headers:{...H(o,e),'Set-Cookie':cookie('admin_session','',0)}})}
if(p==='/api/accounts'){
let s=await session(r,e);
if(m==='GET'){let a=await e.DB.prepare('SELECT id,name,is_primary,EXISTS(SELECT 1 FROM admin_credentials c WHERE c.account_id=admin_accounts.id AND c.code_hash IS NOT NULL) AS code_ready FROM admin_accounts ORDER BY is_primary DESC,name COLLATE NOCASE').all();let invitations=await e.DB.prepare('SELECT account_id,token,expires_at FROM admin_invitations WHERE expires_at>?').bind(Date.now()).all();let map=new Map(invitations.results.map(i=>[i.account_id,i]));return J({accounts:a.results.map(account=>{let invite=!account.code_ready?map.get(account.id):null;return {...account,invitation_expires_at:invite?.expires_at||null,...(s?.is_primary&&invite?{invitation:invite.token}:{})}})},200,o,e)}
if(m==='POST'){if(!s?.is_primary)return J({error:'Only the primary administrator can manage accounts.'},403,o,e);let b=await r.json(),name=String(b.name||'').trim();if(!name||name.length>60)return J({error:'Enter an account name of 1?60 characters.'},400,o,e);if(await e.DB.prepare('SELECT id FROM admin_accounts WHERE name=? COLLATE NOCASE').bind(name).first())return J({error:'That account name already exists.'},409,o,e);let id=uuid(),invitation=uuid(),expires=Date.now()+600000;await e.DB.batch([e.DB.prepare('INSERT INTO admin_accounts(id,name,is_primary) VALUES(?,?,0)').bind(id,name),e.DB.prepare('INSERT INTO admin_account_metadata(account_id,created_at) VALUES(?,?)').bind(id,now()),e.DB.prepare('INSERT INTO admin_credentials(account_id,invitation_hash) VALUES(?,?)').bind(id,await hash(invitation)),saveInvitation(e,id,invitation,expires),audit(e,s,'created_admin',null,null,name),audit(e,s,'generated_admin_invitation',null,null,name)]);return J({ok:true,invitation,expires_at:expires,account_name:name},201,o,e)}
}
if(p==='/api/accounts/select'&&m==='POST')return J({error:'Sign in with the target account personal code.'},403,o,e);
if(p==='/api/accounts/invite'&&m==='POST'){let s=await session(r,e);if(!s?.is_primary)return J({error:'Only the primary administrator can issue invitations.'},403,o,e);let b=await r.json(),account=await e.DB.prepare('SELECT id,name FROM admin_accounts WHERE id=?').bind(b.account_id).first();if(!account)return J({error:'Account not found.'},404,o,e);if((await credential(e,account.id))?.code_hash)return J({error:'Account already has a personal code.'},409,o,e);let invitation=uuid(),expires=Date.now()+600000;let results=await e.DB.batch([e.DB.prepare('INSERT INTO admin_credentials(account_id,invitation_hash) VALUES(?,?) ON CONFLICT(account_id) DO UPDATE SET invitation_hash=excluded.invitation_hash WHERE admin_credentials.code_hash IS NULL').bind(account.id,await hash(invitation)),saveInvitation(e,account.id,invitation,expires),accountAuditAfterChange(e,s,'generated_admin_invitation',account.name)]);let result=results[1];if(!result.meta?.changes)return J({error:'Account already set up.'},409,o,e);return J({invitation,expires_at:expires,account_name:account.name},200,o,e)}
if(p==='/api/accounts/reset-code'&&m==='POST'){
let user=await session(r,e);if(!user?.is_primary)return J({error:'Only the primary administrator can reset account codes.'},403,o,e);
let b=await r.json().catch(()=>({})),account=await e.DB.prepare('SELECT id,name,is_primary FROM admin_accounts WHERE id=?').bind(String(b.account_id||'')).first();
if(!account)return J({error:'Account not found.'},404,o,e);if(account.is_primary)return J({error:'The primary account cannot be reset here.'},403,o,e);
let invitation=uuid(),expires=Date.now()+600000;await e.DB.batch([
e.DB.prepare('INSERT INTO admin_credentials(account_id,invitation_hash) VALUES(?,?) ON CONFLICT(account_id) DO UPDATE SET salt=NULL,code_hash=NULL,invitation_hash=excluded.invitation_hash').bind(account.id,await hash(invitation)),
saveInvitation(e,account.id,invitation,expires),e.DB.prepare('DELETE FROM admin_sessions WHERE account_id=?').bind(account.id),
e.DB.prepare('DELETE FROM admin_login_attempts WHERE account_id=?').bind(account.id),
audit(e,user,'reset_admin_code',null,null,account.name),
audit(e,user,'generated_admin_invitation',null,null,account.name)
]);return J({ok:true,invitation,expires_at:expires,account_name:account.name},200,o,e)}
let statsMatch=p.match(/^\/api\/accounts\/([^/]+)\/stats$/);
if(statsMatch&&m==='GET'){
let user=await session(r,e);if(!user?.is_primary)return J({error:'Only the primary administrator can view account statistics.'},403,o,e);
let id=decodeURIComponent(statsMatch[1]),account=await e.DB.prepare('SELECT a.id,a.name,a.is_primary,m.created_at FROM admin_accounts a LEFT JOIN admin_account_metadata m ON m.account_id=a.id WHERE a.id=?').bind(id).first();if(!account)return J({error:'Account not found.'},404,o,e);
let performed=await e.DB.prepare(`SELECT COUNT(*) AS actions_performed,COUNT(DISTINCT CASE WHEN action IN ('created_player','updated_player') THEN player_id END) AS players_assessed,SUM(CASE WHEN action IN ('created_player','updated_player') THEN 1 ELSE 0 END) AS assessments_saved,SUM(CASE WHEN action='created_player' THEN 1 ELSE 0 END) AS players_created,SUM(CASE WHEN action='updated_player' THEN 1 ELSE 0 END) AS player_updates,SUM(CASE WHEN action='locked_player' THEN 1 ELSE 0 END) AS players_locked,SUM(CASE WHEN action='unlocked_player' THEN 1 ELSE 0 END) AS players_unlocked,MIN(created_at) AS first_activity,MAX(created_at) AS last_activity FROM activity_logs WHERE actor_id=?`).bind(id).first();
let affected=await e.DB.prepare(`SELECT COUNT(*) AS actions_received,SUM(CASE WHEN action='reset_admin_code' THEN 1 ELSE 0 END) AS code_resets_received,SUM(CASE WHEN action='generated_admin_invitation' THEN 1 ELSE 0 END) AS invitations_received FROM activity_logs WHERE account_name=? COLLATE NOCASE AND actor_id<>? AND (? IS NULL OR created_at>=?)`).bind(account.name,id,account.created_at,account.created_at).first();
return J({account,statistics:{...performed,...affected}},200,o,e)}
let accountMatch=p.match(/^\/api\/accounts\/([^/]+)$/);
if(accountMatch&&m==='DELETE'){let s=await session(r,e);if(!s?.is_primary)return J({error:'Only the primary administrator can manage accounts.'},403,o,e);let id=decodeURIComponent(accountMatch[1]),a=await e.DB.prepare('SELECT * FROM admin_accounts WHERE id=?').bind(id).first();if(!a)return J({error:'Account not found.'},404,o,e);if(a.is_primary)return J({error:'The primary account cannot be deleted.'},403,o,e);await e.DB.batch([e.DB.prepare('DELETE FROM admin_sessions WHERE account_id=?').bind(id),e.DB.prepare('DELETE FROM admin_invitations WHERE account_id=?').bind(id),e.DB.prepare('DELETE FROM admin_credentials WHERE account_id=?').bind(id),e.DB.prepare('DELETE FROM admin_account_metadata WHERE account_id=?').bind(id),e.DB.prepare('DELETE FROM admin_accounts WHERE id=?').bind(id),audit(e,s,'deleted_admin',null,null,a.name)]);return J({ok:true},200,o,e)}
if(p==='/api/logs'&&m==='GET'){let q=await guard(r,e,o);if(q)return q;let before=Number(u.searchParams.get('before'))||Number.MAX_SAFE_INTEGER;let logs=await e.DB.prepare('SELECT * FROM activity_logs WHERE id<? ORDER BY id DESC LIMIT 100').bind(before).all();return J({logs:logs.results},200,o,e)}
if(p==='/api/players'&&m==='GET'){let x=await e.DB.prepare('SELECT * FROM players ORDER BY name COLLATE NOCASE').all();return J({players:x.results},200,o,e)}
if(p==='/api/players'&&m==='POST'){let q=await guard(r,e,o);if(q)return q;let b=await r.json(),err=valid(b);if(err)return J({error:err},400,o,e);if(await duplicatePlayer(e,b.name.trim()))return J({error:duplicateNameError},409,o,e);let i=uuid(),t=now();await e.DB.batch([e.DB.prepare('INSERT INTO players(id,name,class_name,overall_tier,control,execution,defending,reaction_time,chemistry,game_sense,playstyle,strengths,weaknesses,assessed_at,locked,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(i,b.name.trim(),b.class_name||'',b.overall_tier,...A.map(k=>Number(b[k])),b.playstyle||'',b.strengths||'',b.weaknesses||'',b.assessed_at,0,t,t),snap(e,{...b,id:i}),audit(e,await session(r,e),'created_player',{...b,id:i,name:b.name.trim()})]);return J({ok:true,id:i},201,o,e)}
let mt=p.match(/^\/api\/players\/([^/]+)(?:\/(lock|unlock))?$/);if(!mt)return J({error:'Not found.'},404,o,e);let id=decodeURIComponent(mt[1]),act=mt[2];
if(m==='GET'){let pl=await e.DB.prepare('SELECT * FROM players WHERE id=?').bind(id).first();if(!pl)return J({error:'Player not found.'},404,o,e);let hs=await e.DB.prepare('SELECT * FROM assessments WHERE player_id=? ORDER BY assessed_at,id').bind(id).all();return J({player:pl,history:hs.results},200,o,e)}
let q=await guard(r,e,o);if(q)return q;let pl=await e.DB.prepare('SELECT * FROM players WHERE id=?').bind(id).first();if(!pl)return J({error:'Player not found.'},404,o,e);
if(act==='lock'&&m==='POST'){await e.DB.batch([e.DB.prepare('UPDATE players SET locked=1,updated_at=? WHERE id=?').bind(now(),id),await playerAudit(r,e,'locked_player',pl)]);return J({ok:true},200,o,e)}
if(act==='unlock'&&m==='POST'){let b=await r.json().catch(()=>({}));let user=await session(r,e),c=await credential(e,user.id);if(!c?.code_hash||await codeHash(String(b.code||''),c.salt)!==c.code_hash)return J({error:'Administrative code is incorrect.'},403,o,e);await e.DB.batch([e.DB.prepare('UPDATE players SET locked=0,updated_at=? WHERE id=?').bind(now(),id),await playerAudit(r,e,'unlocked_player',pl)]);return J({ok:true},200,o,e)}
if(pl.locked)return J({error:'This player is locked. Unlock it from Personal Settings first.'},423,o,e);
if(m==='PUT'){let b=await r.json(),err=valid(b);if(err)return J({error:err},400,o,e);if(await duplicatePlayer(e,b.name.trim(),id))return J({error:duplicateNameError},409,o,e);let result=await e.DB.batch([e.DB.prepare('UPDATE players SET name=?,class_name=?,overall_tier=?,control=?,execution=?,defending=?,reaction_time=?,chemistry=?,game_sense=?,playstyle=?,strengths=?,weaknesses=?,assessed_at=?,updated_at=? WHERE id=? AND locked=0').bind(b.name.trim(),b.class_name||'',b.overall_tier,...A.map(k=>Number(b[k])),b.playstyle||'',b.strengths||'',b.weaknesses||'',b.assessed_at,now(),id),snap(e,{...b,id},true),audit(e,await session(r,e),'updated_player',{...b,id,name:b.name.trim()},null,null,true)]);if(!result[0].meta?.changes)return J({error:'This player was locked. Your changes were not saved.'},423,o,e);return J({ok:true},200,o,e)}
if(m==='DELETE'){await e.DB.batch([await playerAudit(r,e,'deleted_player',pl),e.DB.prepare('DELETE FROM assessments WHERE player_id=?').bind(id),e.DB.prepare('DELETE FROM players WHERE id=?').bind(id)]);return J({ok:true},200,o,e)}
return J({error:'Not found.'},404,o,e)}
export default{async fetch(r,e){try{await e.DB.prepare('DELETE FROM admin_sessions WHERE expires_at<=?').bind(Date.now()).run();return await main(r,e)}catch(x){if(/UNIQUE constraint failed.*idx_players_unique_name/i.test(String(x?.message||x)))return J({error:duplicateNameError},409,r.headers.get('Origin')||'',e);return J({error:'Server error.'},500,r.headers.get('Origin')||'',e)}}};
